
# Traits
adept = Trait.create(name: "Adept", description: "Adepts calm the flow of battle, reducing the Attack Speed of all enemies for a few seconds at the start of combat.")
assassin = Trait.create(name: "Assassin", description: "Assassins gain bonus Critical Strike Damage and Chance, and their spells can critically strike.")
brawler = Trait.create(name: "Brawler", description: "Brawlers gain bonus Health.")
cultist = Trait.create(name: "Cultist", description: "Once your team loses a percentage of their Health, Galio is summoned, slamming into the largest cluster of enemies and knocking them up.")
dazzler = Trait.create(name: "Dazzler", description: "Dazzlers' spells reduce the Attack Damage of enemies hit for a few seconds.")
divine = Trait.create(name: "Divine", description: "Upon attacking several times or dropping below a percentage of their Health, Divine champions ascend, taking reduced damage and dealing bonus true damage for the rest of combat.")
duelist = Trait.create(name: "Duelist", description: "Duelists' attacks grant Attack Speed.")
dusk = Trait.create(name: "Dusk", description: "Dusk champions increase all allies' Spell Power.")
elderwood = Trait.create(name: "Elderwood", description: "Every two seconds all Elderwood champions grow, gaining bonus stats. This effect stacks up to five times.")
enlightened = Trait.create(name: "Enlightened", description: "Enlightened champions generate more Mana.")

# Units

aatrox = Unit.create(name: "Aatrox", image: "TFT4_Aatrox.png",  cost: 4)
ahri = Unit.create(name: "Ahri", image: "TFT4_Ahri.png",  cost: 4)
akali = Unit.create(name: "Akali", image: "TFT4_Akali.png", cost: 3)
annie = Unit.create(name: "Annie", image: "TFT4_Annie.png",  cost: 2)
aphelios = Unit.create(name: "Aphelios", image: "TFT4_Aphelios.png",  cost: 2)
ashe = Unit.create(name: "Ashe", image: "TFT4_Ashe.png",  cost: 4)
azir = Unit.create(name: "Azir", image: "TFT4_Azir.png",  cost: 5)
cassiopeia = Unit.create(name: "Cassiopeia", image: "TFT4_Cassiopeia.png", cost: 4)
diana = Unit.create(name: "Diana", image: "TFT4_Diana.png",  cost: 1)
elise = Unit.create(name: "Elise", image: "TFT4_Elise.png", cost: 1)
evelynn = Unit.create(name: "Evelynn", image: "TFT4_Evelynn.png", cost: 3)
ezreal = Unit.create(name: "Ezreal", image: "TFT4_Ezreal.png", cost: 5)
fiora = Unit.create(name: "Fiora", image: "TFT4_Fiora.png", cost: 1)
garen = Unit.create(name: "Garen", image: "TFT4_Garen.png", cost: 1)
hecarim = Unit.create(name: "Hecarim", image: "TFT4_Hecarim.png", cost: 2)
irelia = Unit.create(name: "Irelia", image: "TFT4_Irelia.png", cost: 3)
janna = Unit.create(name: "Janna", image: "TFT4_Janna.png", cost: 2)
katarina = Unit.create(name: "Katarina", image: "TFT4_Katarina.png", cost: 3)
kayn = Unit.create(name: "Kayn", image: "TFT4_Kayn.png", cost: 5)
sejuani = Unit.create(name: "Sejuani", image: "TFT4_Sejuani.png", cost: 4)
